# 开启自动更新
auto-update: true

# 不要修改这个内容
config-version: 209-Alpha-38

integrations:
  # 不推荐开启
  guide:
    survival-override: false
    cheat-override: false

drawer-auto-save-period: 300

# max-distance 最大距离限制
# pushitem-tick 1 SF Tick=0.5秒 推送物品的时间
# grabitem-tick 1 SF Tick=0.5秒 抓取物品的时间
# required-power 抓取和推送分别每次网络电力消耗
items:
  # 链式传输器[推送]
  NTW_EXPANSION_LINE_TRANSFER_PUSHER:
    max-distance: 32
    pushitem-tick: 1
    use-special-model:
      enable: false
  # 链式传输器[抓取]
  NTW_EXPANSION_LINE_TRANSFER_GRABBER:
    max-distance: 32
    grabitem-tick: 1
    use-special-model:
      enable: false
  # 链式传输器
  NTW_EXPANSION_LINE_TRANSFER:
    max-distance: 32
    pushitem-tick: 1
    grabitem-tick: 1
    use-special-model:
      enable: false
  # 链式传输器Plus[推送]
  NTW_EXPANSION_LINE_TRANSFER_PLUS_PUSHER:
    max-distance: 64
    pushitem-tick: 1
    use-special-model:
      enable: false
  # 链式传输器Plus[抓取]
  NTW_EXPANSION_LINE_TRANSFER_PLUS_GRABBER:
    max-distance: 64
    grabitem-tick: 1
    use-special-model:
      enable: false
  # 链式传输器Plus
  NTW_EXPANSION_LINE_TRANSFER_PLUS:
    max-distance: 64
    pushitem-tick: 1
    grabitem-tick: 1
    required-power: 5000
    use-special-model:
      enable: false
  # 高级链式传输器[推送]
  NTW_EXPANSION_ADVANCED_LINE_TRANSFER_PUSHER:
    max-distance: 32
    pushitem-tick: 1
    use-special-model:
      enable: false
  # 高级链式传输器[抓取]
  NTW_EXPANSION_ADVANCED_LINE_TRANSFER_GRABBER:
    max-distance: 32
    grabitem-tick: 1
    use-special-model:
      enable: false
  # 高级链式传输器
  NTW_EXPANSION_ADVANCED_LINE_TRANSFER:
    max-distance: 32
    pushitem-tick: 1
    grabitem-tick: 1
    use-special-model:
      enable: false
  # 高级链式传输器Plus[推送]
  NTW_EXPANSION_ADVANCED_LINE_TRANSFER_PLUS_PUSHER:
    max-distance: 64
    pushitem-tick: 1
    use-special-model:
      enable: false
  # 高级链式传输器Plus[抓取]
  NTW_EXPANSION_ADVANCED_LINE_TRANSFER_PLUS_GRABBER:
    max-distance: 64
    grabitem-tick: 1
    use-special-model:
      enable: false
  # 高级链式传输器Plus
  NTW_EXPANSION_ADVANCED_LINE_TRANSFER_PLUS:
    max-distance: 64
    pushitem-tick: 1
    grabitem-tick: 1
    required-power: 5000
    use-special-model:
      enable: false
  # 原版链式传输器[推送]
  NTW_EXPANSION_LINE_TRANSFER_VANILLA_PUSHER:
    max-distance: 32
    pushitem-tick: 1
    use-special-model:
      enable: false
  # 原版链式传输器[抓取]
  NTW_EXPANSION_LINE_TRANSFER_VANILLA_GRABBER:
    max-distance: 32
    grabitem-tick: 1
    use-special-model:
      enable: false

  # 货运存储单元1
  CARGO_STORAGE_UNIT_1_MODEL:
    use-special-model:
      enable: true
      type: "1"
  # 货运存储单元2
  CARGO_STORAGE_UNIT_2_MODEL:
    use-special-model:
      enable: true
      type: "2"
  # 货运存储单元3
  CARGO_STORAGE_UNIT_3_MODEL:
    use-special-model:
      enable: true
      type: "3"
  # 货运存储单元4
  CARGO_STORAGE_UNIT_4_MODEL:
    use-special-model:
      enable: true
      type: "4"
  # 货运存储单元5
  CARGO_STORAGE_UNIT_5_MODEL:
    use-special-model:
      enable: true
      type: "5"
  # 货运存储单元6
  CARGO_STORAGE_UNIT_6_MODEL:
    use-special-model:
      enable: true
      type: "6"
  # 货运存储单元7
  CARGO_STORAGE_UNIT_7_MODEL:
    use-special-model:
      enable: true
      type: "7"
  # 货运存储单元8
  CARGO_STORAGE_UNIT_8_MODEL:
    use-special-model:
      enable: true
      type: "8"
  # 货运存储单元9
  CARGO_STORAGE_UNIT_9_MODEL:
    use-special-model:
      enable: true
      type: "9"
  # 货运存储单元10
  CARGO_STORAGE_UNIT_10_MODEL:
    use-special-model:
      enable: true
      type: "10"
  # 货运存储单元11
  CARGO_STORAGE_UNIT_11_MODEL:
    use-special-model:
      enable: true
      type: "11"
  # 货运存储单元12
  CARGO_STORAGE_UNIT_12_MODEL:
    use-special-model:
      enable: true
      type: "12"
  # 货运存储单元13
  CARGO_STORAGE_UNIT_13_MODEL:
    use-special-model:
      enable: true
      type: "13"
  NTW_EXPANSION_LINE_POWER_OUTLET_1:
    max-distance: 32
    rate: 64
  NTW_EXPANSION_LINE_POWER_OUTLET_2:
    max-distance: 32
    rate: 256
  NTW_EXPANSION_LINE_POWER_OUTLET_3:
    max-distance: 32
    rate: 1024
  NTW_EXPANSION_LINE_POWER_OUTLET_4:
    max-distance: 32
    rate: 4096
  NTW_EXPANSION_LINE_POWER_OUTLET_5:
    max-distance: 32
    rate: 32768
  NTW_EXPANSION_LINE_POWER_OUTLET_6:
    max-distance: 32
    rate: 262144
  NTW_EXPANSION_LINE_POWER_OUTLET_7:
    max-distance: 32
    rate: 2097152
  NTW_EXPANSION_LINE_POWER_OUTLET_8:
    max-distance: 32
    rate: 16777216
  NTW_EXPANSION_LINE_POWER_OUTLET_9:
    max-distance: 32
    rate: 134217728
  NTW_EXPANSION_LINE_POWER_OUTLET_10:
    max-distance: 32
    rate: 1073741824
  NTW_EXPANSION_LINE_POWER_OUTLET_11:
    max-distance: 32
    rate: 2147483647